-- M00 Foundation (design 4.3 "Administration & system", 5.3, 5.7)
-- Users, audit log, document sequences, settings and login lock.

-- ---------------------------------------------------------------- users
CREATE TABLE app_user (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(50)  NOT NULL,
    full_name            VARCHAR(100) NOT NULL,
    phone                VARCHAR(20),
    role                 VARCHAR(20)  NOT NULL,
    password_hash        VARCHAR(100) NOT NULL,
    must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at        TIMESTAMPTZ,
    token_version        INTEGER      NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by           VARCHAR(50)  NOT NULL DEFAULT 'system',
    updated_at           TIMESTAMPTZ,
    updated_by           VARCHAR(50),
    version              BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ux_app_user_username UNIQUE (username),
    CONSTRAINT ck_app_user_username_lower CHECK (username = lower(username) AND length(trim(username)) > 0),
    CONSTRAINT ck_app_user_role CHECK (role IN ('ADMIN', 'ACCOUNTANT', 'DELIVERY_STAFF')),
    CONSTRAINT ck_app_user_token_version CHECK (token_version >= 0)
);

-- ---------------------------------------------------------------- audit log (insert-only, FR-57)
CREATE TABLE audit_log (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts       TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id  BIGINT REFERENCES app_user (id),
    username VARCHAR(50),
    role     VARCHAR(20),
    action   VARCHAR(20) NOT NULL,
    entity   VARCHAR(50) NOT NULL,
    ref      VARCHAR(50),
    details  TEXT,
    ip       VARCHAR(45),
    CONSTRAINT ck_audit_log_action CHECK (action IN ('CREATE', 'UPDATE', 'APPROVE', 'REVERSE', 'IMPORT', 'LOGIN', 'LOGOUT'))
);
CREATE INDEX ix_audit_log_ts ON audit_log (ts);
CREATE INDEX ix_audit_log_entity_ref ON audit_log (entity, ref);
CREATE INDEX ix_audit_log_user ON audit_log (user_id, ts);

-- Audit rows are never changed or removed – not even by mistake from SQL.
CREATE FUNCTION audit_log_insert_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'audit_log is insert-only';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_audit_log_insert_only
    BEFORE UPDATE OR DELETE ON audit_log
    FOR EACH ROW EXECUTE FUNCTION audit_log_insert_only();

-- ---------------------------------------------------------------- document numbers (design 5.3)
CREATE TABLE doc_sequence (
    name        VARCHAR(40) PRIMARY KEY,
    prefix      VARCHAR(10) NOT NULL,
    next_value  BIGINT      NOT NULL DEFAULT 1,
    padding     INTEGER     NOT NULL,
    reset_rule  VARCHAR(10) NOT NULL DEFAULT 'NONE',
    period_key  VARCHAR(4),
    description VARCHAR(100),
    CONSTRAINT ck_doc_sequence_next CHECK (next_value >= 1),
    CONSTRAINT ck_doc_sequence_padding CHECK (padding BETWEEN 1 AND 10),
    CONSTRAINT ck_doc_sequence_reset CHECK (reset_rule IN ('NONE', 'YEARLY', 'MONTHLY'))
);

INSERT INTO doc_sequence (name, prefix, padding, reset_rule, description) VALUES
    ('CUSTOMER',           'C',    4, 'NONE',    'Customer code C0001'),
    ('PRODUCT',            'P',    2, 'NONE',    'Product code P01'),
    ('SUPPLIER',           'S',    2, 'NONE',    'Supplier code S01'),
    ('FACTORY',            'F',    2, 'NONE',    'Filling factory code F01'),
    ('QUOTATION_REQUEST',  'QR-',  3, 'YEARLY',  'Quotation request QR-2026-001'),
    ('SUPPLIER_QUOTATION', 'SQ-',  4, 'NONE',    'Supplier quotation SQ-0001'),
    ('CUSTOMER_QUOTATION', 'QT-',  3, 'YEARLY',  'Customer quotation QT-2026-001'),
    ('PURCHASE_ORDER',     'PO-',  4, 'YEARLY',  'Purchase order PO-2026-0001'),
    ('GOODS_RECEIPT',      'GRN-', 4, 'NONE',    'Goods receipt GRN-0001'),
    ('FACTORY_DISPATCH',   'FD-',  4, 'NONE',    'Factory dispatch FD-0001'),
    ('FACTORY_BATCH',      'FB-',  4, 'NONE',    'Factory batch FB-0001'),
    ('FACTORY_RETURN',     'FR-',  4, 'NONE',    'Factory return FR-0001'),
    ('FACTORY_PAYMENT',    'FP-',  4, 'NONE',    'Factory payment FP-0001'),
    ('BILL',               'B',    6, 'NONE',    'Bill (every sales transaction, incl. reversals) B000001'),
    ('RECEIPT',            'RC-',  5, 'NONE',    'Payment receipt RC-00001'),
    ('MONTHLY_INVOICE',    'INV-', 4, 'MONTHLY', 'Monthly invoice INV-YYMM-0001'),
    ('STOCK_ADJUSTMENT',   'ADJ-', 4, 'NONE',    'Stock adjustment ADJ-0001'),
    ('SUPPLIER_PAYMENT',   'SP-',  4, 'NONE',    'Supplier payment SP-0001'),
    ('EXPENSE',            'EX-',  4, 'NONE',    'Expense EX-0001'),
    ('CUSTOMER_PRICE',     'CP',   4, 'NONE',    'Customer agreed price CP0001');

-- ---------------------------------------------------------------- settings
CREATE TABLE app_setting (
    key        VARCHAR(50) PRIMARY KEY,
    value      JSONB       NOT NULL,
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(50),
    CONSTRAINT ck_app_setting_object CHECK (jsonb_typeof(value) = 'object')
);

-- Company details are the prototype's placeholders until the client confirms them (BRD open items).
INSERT INTO app_setting (key, value) VALUES
    ('company', '{"name": "Thuhina Water (Pvt) Ltd", "address": "No. 48, High Level Road, Nugegoda", "phone": "011 285 4471", "email": "accounts@thuhinawater.lk", "regNo": "PV 00231877", "logo": null}'),
    ('business', '{"currency": "LKR", "timeZone": "Asia/Colombo", "dateFormat": "DD/MM/YYYY"}'),
    ('features', '{"dataMigration": false}');

-- ---------------------------------------------------------------- login lock (design 8.1)
CREATE TABLE login_attempt (
    username       VARCHAR(50) PRIMARY KEY,
    failed_count   INTEGER     NOT NULL DEFAULT 0,
    last_failed_at TIMESTAMPTZ,
    locked_until   TIMESTAMPTZ,
    CONSTRAINT ck_login_attempt_count CHECK (failed_count >= 0)
);
