-- M02 Master data (design 4.3 "Master data", 5.5)
-- Bottle types, other products, customer types, areas, dated standard prices and deposits, accepted old-bottle brands.

-- ---------------------------------------------------------------- bottle types (FR-01)
-- The code comes from the size: B + litres (19 → B19, 0.5 → B0_5). Other tables refer to the code.
CREATE TABLE bottle_type (
    code       VARCHAR(10)  PRIMARY KEY,
    name       VARCHAR(60)  NOT NULL,
    litres     NUMERIC(6,2) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by VARCHAR(50)  NOT NULL DEFAULT 'system',
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(50),
    version    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ux_bottle_type_litres UNIQUE (litres),
    CONSTRAINT ck_bottle_type_litres CHECK (litres > 0),
    CONSTRAINT ck_bottle_type_code CHECK (code ~ '^B[0-9]+(_[0-9]+)?$')
);

-- ---------------------------------------------------------------- other products (FR-02)
CREATE TABLE product (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(10)   NOT NULL,
    name          VARCHAR(100)  NOT NULL,
    selling_price NUMERIC(12,2) NOT NULL,
    cost_price    NUMERIC(12,2),
    stock_qty     INTEGER       NOT NULL DEFAULT 0,
    active        BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by    VARCHAR(50)   NOT NULL DEFAULT 'system',
    updated_at    TIMESTAMPTZ,
    updated_by    VARCHAR(50),
    version       BIGINT        NOT NULL DEFAULT 0,
    CONSTRAINT ux_product_code UNIQUE (code),
    CONSTRAINT ck_product_selling_price CHECK (selling_price > 0),
    CONSTRAINT ck_product_cost_price CHECK (cost_price IS NULL OR cost_price >= 0),
    CONSTRAINT ck_product_stock CHECK (stock_qty >= 0)
);

-- ---------------------------------------------------------------- customer types (FR-03) and areas (delivery routes)
CREATE TABLE customer_type (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    description VARCHAR(200),
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(50)  NOT NULL DEFAULT 'system',
    updated_at  TIMESTAMPTZ,
    updated_by  VARCHAR(50),
    version     BIGINT       NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_customer_type_name ON customer_type (lower(name));

CREATE TABLE area (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(60)  NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by VARCHAR(50)  NOT NULL DEFAULT 'system',
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(50),
    version    BIGINT       NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_area_name ON area (lower(name));

-- ---------------------------------------------------------------- standard prices and deposits (FR-04, FR-07, BR-08)
-- Insert-only price history: a change is a new row with its effective date. The price for a date is the row with the
-- latest effective_from on or before that date. WATER rows have a customer type; DEPOSIT rows have none.
CREATE TABLE price_entry (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind             VARCHAR(10)   NOT NULL,
    bottle_type_code VARCHAR(10)   NOT NULL REFERENCES bottle_type (code),
    customer_type_id BIGINT        REFERENCES customer_type (id),
    price            NUMERIC(12,2) NOT NULL,
    effective_from   DATE          NOT NULL,
    reason           VARCHAR(200)  NOT NULL,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       VARCHAR(50)   NOT NULL DEFAULT 'system',
    CONSTRAINT ck_price_entry_kind CHECK (kind IN ('WATER', 'DEPOSIT')),
    CONSTRAINT ck_price_entry_type CHECK ((kind = 'WATER') = (customer_type_id IS NOT NULL)),
    CONSTRAINT ck_price_entry_price CHECK (price > 0),
    CONSTRAINT ux_price_entry UNIQUE NULLS NOT DISTINCT (kind, bottle_type_code, customer_type_id, effective_from)
);
CREATE INDEX ix_price_entry_lookup ON price_entry (kind, bottle_type_code, customer_type_id, effective_from DESC);

CREATE FUNCTION price_entry_insert_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'price_entry is insert-only – add a new entry with an effective date instead';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_price_entry_insert_only
    BEFORE UPDATE OR DELETE ON price_entry
    FOR EACH ROW EXECUTE FUNCTION price_entry_insert_only();

-- ---------------------------------------------------------------- accepted old-bottle brands (FR-06, BR-02)
CREATE TABLE old_bottle_brand (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(60)  NOT NULL,
    bottle_type_code VARCHAR(10)  NOT NULL REFERENCES bottle_type (code),
    note             VARCHAR(200),
    active           BOOLEAN      NOT NULL DEFAULT TRUE,
    added_on         DATE         NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       VARCHAR(50)  NOT NULL DEFAULT 'system',
    updated_at       TIMESTAMPTZ,
    updated_by       VARCHAR(50),
    version          BIGINT       NOT NULL DEFAULT 0
);
CREATE UNIQUE INDEX ux_old_bottle_brand ON old_bottle_brand (lower(name), bottle_type_code);

-- ---------------------------------------------------------------- confirmed prices
-- Prices are "example" until the client confirms them. Keys: DEPOSIT|<bottle> or WATER|<bottle>|<customer type name>.
-- The Rs. 1,000 deposit for a 20L bottle is confirmed (BRD BR-01).
INSERT INTO app_setting (key, value) VALUES ('prices', '{"confirmed": ["DEPOSIT|B20"]}');
