-- M03 Suppliers & factories (design 4.3 "Partners")
-- Suppliers with the items they supply, filling factories with a dated charge per bottle type.
-- Codes come from the SUPPLIER (S01) and FACTORY (F01) sequences created in V001.

-- ---------------------------------------------------------------- suppliers (FR-14)
CREATE TABLE supplier (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(10)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    contact    VARCHAR(100),
    phone      VARCHAR(20)  NOT NULL,
    email      VARCHAR(100),
    address    VARCHAR(200),
    terms_days INTEGER      NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by VARCHAR(50)  NOT NULL DEFAULT 'system',
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(50),
    version    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ux_supplier_code UNIQUE (code),
    CONSTRAINT ck_supplier_terms CHECK (terms_days IN (0, 7, 14, 30, 45, 60))
);

-- What a supplier supplies: empty bottles (bottle type code) or products (product code). At least one per supplier
-- (checked by the service).
CREATE TABLE supplier_item (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT      NOT NULL REFERENCES supplier (id) ON DELETE CASCADE,
    item_type   VARCHAR(10) NOT NULL,
    item_code   VARCHAR(10) NOT NULL,
    CONSTRAINT ck_supplier_item_type CHECK (item_type IN ('BOTTLE', 'PRODUCT')),
    CONSTRAINT ux_supplier_item UNIQUE (supplier_id, item_type, item_code)
);
CREATE INDEX ix_supplier_item_item ON supplier_item (item_type, item_code);

-- ---------------------------------------------------------------- filling factories (FR-22, BR-11)
CREATE TABLE factory (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(10)  NOT NULL,
    name       VARCHAR(100) NOT NULL,
    address    VARCHAR(200),
    contact    VARCHAR(100),
    phone      VARCHAR(20),
    email      VARCHAR(100),
    licence    VARCHAR(100),
    terms_days INTEGER      NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by VARCHAR(50)  NOT NULL DEFAULT 'system',
    updated_at TIMESTAMPTZ,
    updated_by VARCHAR(50),
    version    BIGINT       NOT NULL DEFAULT 0,
    CONSTRAINT ux_factory_code UNIQUE (code),
    CONSTRAINT ck_factory_terms CHECK (terms_days IN (0, 7, 14, 30, 45, 60))
);

-- Filling charge per bottle (not per litre). Insert-only history: a change is a new row effective from the day it is
-- saved; the charge in force is the newest row on or before the date. Batches copy the charge at dispatch (M10),
-- so a new charge applies only to batches sent after saving.
CREATE TABLE factory_charge (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    factory_id       BIGINT        NOT NULL REFERENCES factory (id),
    bottle_type_code VARCHAR(10)   NOT NULL REFERENCES bottle_type (code),
    charge           NUMERIC(12,2) NOT NULL,
    effective_from   DATE          NOT NULL,
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by       VARCHAR(50)   NOT NULL DEFAULT 'system',
    CONSTRAINT ck_factory_charge CHECK (charge > 0)
);
CREATE INDEX ix_factory_charge_lookup ON factory_charge (factory_id, bottle_type_code, effective_from DESC, id DESC);

CREATE FUNCTION factory_charge_insert_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'factory_charge is insert-only – save a new charge instead';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_factory_charge_insert_only
    BEFORE UPDATE OR DELETE ON factory_charge
    FOR EACH ROW EXECUTE FUNCTION factory_charge_insert_only();
