-- M04 Inventory core (design 4.3 "Inventory & ledger", 5.1 Ledger Engine)
-- Stock by status per bottle type, the ledger (effects + movements), company damage, stock adjustments, minimum levels.

-- ---------------------------------------------------------------- stock balance (five buckets per bottle type)
-- BR-12 is enforced in the Ledger Engine (clear message) and here as a last guard.
CREATE TABLE stock_balance (
    bottle_type_code VARCHAR(10) NOT NULL REFERENCES bottle_type (code),
    bucket           VARCHAR(12) NOT NULL,
    qty              INTEGER     NOT NULL DEFAULT 0,
    PRIMARY KEY (bottle_type_code, bucket),
    CONSTRAINT ck_stock_balance_bucket CHECK (bucket IN ('EMPTY', 'FACTORY', 'FILLED', 'CUSTOMERS', 'WRITTEN_OFF')),
    CONSTRAINT ck_stock_balance_qty CHECK (qty >= 0)
);

-- Back-fill the rows of existing bottle types; new bottle types get theirs from the trigger below
-- (also covers bottle types added by seed scripts).
INSERT INTO stock_balance (bottle_type_code, bucket)
SELECT b.code, k.bucket
FROM bottle_type b
CROSS JOIN (VALUES ('EMPTY'), ('FACTORY'), ('FILLED'), ('CUSTOMERS'), ('WRITTEN_OFF')) AS k (bucket);

CREATE FUNCTION bottle_type_stock_rows() RETURNS trigger AS $$
BEGIN
    INSERT INTO stock_balance (bottle_type_code, bucket)
    SELECT NEW.code, k.bucket
    FROM (VALUES ('EMPTY'), ('FACTORY'), ('FILLED'), ('CUSTOMERS'), ('WRITTEN_OFF')) AS k (bucket)
    ON CONFLICT DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_bottle_type_stock_rows
    AFTER INSERT ON bottle_type
    FOR EACH ROW EXECUTE FUNCTION bottle_type_stock_rows();

-- ---------------------------------------------------------------- ledger (insert-only)
-- One row per effect of a posting. source = the document that caused it (damage, adjustment, bill, GRN, batch …).
CREATE TABLE ledger_effect (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_type      VARCHAR(20)  NOT NULL,
    source_id        BIGINT,
    doc_no           VARCHAR(30),
    target           VARCHAR(20)  NOT NULL,
    bottle_type_code VARCHAR(10)  REFERENCES bottle_type (code),
    product_code     VARCHAR(10),
    customer_id      BIGINT,
    field            VARCHAR(12)  NOT NULL,
    delta            INTEGER      NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       VARCHAR(50)  NOT NULL DEFAULT 'system',
    CONSTRAINT ck_ledger_effect_source CHECK (source_type IN ('SALES_TXN', 'GRN', 'BATCH', 'RETURN', 'DAMAGE', 'ADJUSTMENT', 'IMPORT')),
    CONSTRAINT ck_ledger_effect_target CHECK (target IN ('STOCK', 'CUSTOMER_BOTTLE', 'PRODUCT')),
    CONSTRAINT ck_ledger_effect_delta CHECK (delta <> 0)
);
CREATE INDEX ix_ledger_effect_source ON ledger_effect (source_type, source_id);

-- History for the Movements tab and reports: one row per item and bucket of a posting.
CREATE TABLE stock_movement (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movement_date DATE         NOT NULL,
    source_type   VARCHAR(20)  NOT NULL,
    source_id     BIGINT,
    doc_no        VARCHAR(30),
    item_code     VARCHAR(10)  NOT NULL,
    bucket        VARCHAR(12)  NOT NULL,
    qty_delta     INTEGER      NOT NULL,
    description   VARCHAR(300) NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by    VARCHAR(50)  NOT NULL DEFAULT 'system',
    CONSTRAINT ck_stock_movement_bucket CHECK (bucket IN ('EMPTY', 'FACTORY', 'FILLED', 'CUSTOMERS', 'WRITTEN_OFF', 'STOCK'))
);
CREATE INDEX ix_stock_movement_date ON stock_movement (movement_date);
CREATE INDEX ix_stock_movement_item_date ON stock_movement (item_code, movement_date);
CREATE INDEX ix_stock_movement_source ON stock_movement (source_type, source_id);

CREATE FUNCTION ledger_insert_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '% is insert-only – post a reversal instead', TG_TABLE_NAME;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tr_ledger_effect_insert_only BEFORE UPDATE OR DELETE ON ledger_effect
    FOR EACH ROW EXECUTE FUNCTION ledger_insert_only();
CREATE TRIGGER tr_stock_movement_insert_only BEFORE UPDATE OR DELETE ON stock_movement
    FOR EACH ROW EXECUTE FUNCTION ledger_insert_only();

-- ---------------------------------------------------------------- damage (FR-29, BR-05; customer damage in M06)
CREATE TABLE damage_record (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    damage_no        VARCHAR(20)  NOT NULL,
    damage_date      DATE         NOT NULL,
    bottle_type_code VARCHAR(10)  NOT NULL REFERENCES bottle_type (code),
    qty              INTEGER      NOT NULL,
    responsibility   VARCHAR(10)  NOT NULL,
    location         VARCHAR(30),
    reason           VARCHAR(200) NOT NULL,
    note             VARCHAR(300),
    customer_id      BIGINT,
    source_type      VARCHAR(20),
    source_id        BIGINT,
    reversed         BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by       VARCHAR(50)  NOT NULL DEFAULT 'system',
    CONSTRAINT ux_damage_record_no UNIQUE (damage_no),
    CONSTRAINT ck_damage_record_qty CHECK (qty >= 1),
    CONSTRAINT ck_damage_record_resp CHECK (responsibility IN ('COMPANY', 'CUSTOMER')),
    CONSTRAINT ck_damage_record_location CHECK (location IS NULL OR location IN ('EMPTY_IN_STORE', 'FILLED_IN_STORE', 'AT_FACTORY', 'DURING_DELIVERY'))
);
CREATE INDEX ix_damage_record_date ON damage_record (damage_date);

-- ---------------------------------------------------------------- stock adjustments (FR-30)
CREATE TABLE stock_adjustment (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    adj_no      VARCHAR(20)  NOT NULL,
    adj_date    DATE         NOT NULL,
    item_code   VARCHAR(10)  NOT NULL,
    bucket      VARCHAR(12)  NOT NULL,
    mode        VARCHAR(10)  NOT NULL,
    system_qty  INTEGER      NOT NULL,
    counted_qty INTEGER,
    delta       INTEGER      NOT NULL,
    reason      VARCHAR(200) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(50)  NOT NULL DEFAULT 'system',
    CONSTRAINT ux_stock_adjustment_no UNIQUE (adj_no),
    CONSTRAINT ck_stock_adjustment_mode CHECK (mode IN ('COUNT', 'LOST')),
    CONSTRAINT ck_stock_adjustment_bucket CHECK (bucket IN ('EMPTY', 'FACTORY', 'FILLED', 'STOCK')),
    CONSTRAINT ck_stock_adjustment_delta CHECK (delta <> 0)
);
CREATE INDEX ix_stock_adjustment_date ON stock_adjustment (adj_date);

-- ---------------------------------------------------------------- minimum filled level per bottle type (FR-31)
CREATE TABLE min_stock_level (
    bottle_type_code VARCHAR(10) PRIMARY KEY REFERENCES bottle_type (code),
    min_filled       INTEGER     NOT NULL,
    updated_at       TIMESTAMPTZ,
    updated_by       VARCHAR(50),
    CONSTRAINT ck_min_stock_level CHECK (min_filled >= 0)
);

-- Damage records are numbered DMG-0001 (the STOCK_ADJUSTMENT sequence ADJ-0001 exists since V001).
INSERT INTO doc_sequence (name, prefix, padding, reset_rule, description)
VALUES ('DAMAGE', 'DMG-', 4, 'NONE', 'Damage record DMG-0001');
