/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit name, username, role and phone */
        put: operations["update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/{group}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a settings group: company, business or features */
        get: operations["get"];
        /** Change some keys of a settings group; returns the whole group. The company logo has its own upload */
        put: operations["update_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change name, prices or active – not the stock */
        put: operations["update_2"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/old-bottle-brands/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Stop accepting / accept again, or change the note or bottle type */
        put: operations["update_3"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the description or active – the name cannot change */
        put: operations["updateCustomerType"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bottle-types/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change the name or active – the size cannot change */
        put: operations["update_4"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rename an area or change active */
        put: operations["updateArea"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All users, active first, then by name */
        get: operations["list"];
        put?: never;
        /** Create a user with a temporary password (changed at the first login) */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Issue a new temporary password – returned only in this response */
        post: operations["resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate a user (logs them out at once; not your own account) */
        post: operations["deactivate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate a user */
        post: operations["activate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/company/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The company logo image (any logged-in user – it appears on printed documents) */
        get: operations["logoImage"];
        put?: never;
        /** Upload the company logo (PNG or JPG, at most 1 MB); returns the company settings */
        post: operations["uploadLogo"];
        /** Remove the company logo; returns the company settings */
        delete: operations["removeLogo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All products by code */
        get: operations["list_1"];
        put?: never;
        /** New product – code P01… on save; opening stock only here */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change a price from a date (today or later) with a reason – a new entry; history is kept */
        post: operations["setPrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/old-bottle-brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accepted brands, active first */
        get: operations["list_2"];
        put?: never;
        /** Add an accepted brand for a bottle type */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customer-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer types in the order they were added */
        get: operations["customerTypes"];
        put?: never;
        /** New customer type (unique name) */
        post: operations["createCustomerType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bottle-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bottle types, largest first; activeOnly=true for the pick lists of sales and purchasing */
        get: operations["list_3"];
        put?: never;
        /** New bottle type – the code is made from the size (19 → B19) */
        post: operations["create_3"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log out; clears the login cookie */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in; sets the httpOnly login cookie and returns the user, permissions and menu */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change your own password (at least 8 characters, not the same as the old one) */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Areas (delivery routes) by name */
        get: operations["areas"];
        put?: never;
        /** New area (unique name) */
        post: operations["createArea"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roles/matrix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Menu pages and special rights × roles → FULL / VIEW / NONE */
        get: operations["matrix"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every price entry, newest first, marked Current / Scheduled / Old */
        get: operations["history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prices/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Water price grid and deposits on a date (default today), with the next scheduled change */
        get: operations["current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The logged-in user, role, permissions, landing page and sidebar menu */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search the audit log, newest first. Dates are business dates (ISO); 'to' includes the whole day */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit-log/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users, actions and record types for the filter drop-downs */
        get: operations["filters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateUserRequest: {
            fullName: string;
            username: string;
            /** @enum {string} */
            role: "ADMIN" | "ACCOUNTANT" | "DELIVERY_STAFF";
            phone?: string;
            /** Format: int64 */
            version?: number;
        };
        UserResponse: {
            /** Format: int64 */
            id: number;
            username: string;
            fullName: string;
            phone: string | null;
            role: string;
            roleName: string;
            active: boolean;
            mustChangePassword: boolean;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** Format: int64 */
            version: number;
        };
        JsonNode: {
            /** @enum {string} */
            nodeType: "ARRAY" | "BINARY" | "BOOLEAN" | "MISSING" | "NULL" | "NUMBER" | "OBJECT" | "POJO" | "STRING";
            string: boolean;
            integralNumber: boolean;
            missingNode: boolean;
            valueNode: boolean;
            container: boolean;
            object: boolean;
            pojo: boolean;
            floatingPointNumber: boolean;
            short: boolean;
            int: boolean;
            long: boolean;
            double: boolean;
            bigDecimal: boolean;
            bigInteger: boolean;
            /** @deprecated */
            textual: boolean;
            boolean: boolean;
            binary: boolean;
            array: boolean;
            empty: boolean;
            null: boolean;
            float: boolean;
            number: boolean;
            embeddedValue: boolean;
        };
        UpdateProductRequest: {
            name: string;
            sellingPrice: number;
            costPrice?: number;
            active?: boolean;
            /** Format: int64 */
            version?: number;
        };
        ProductResponse: {
            /** Format: int64 */
            id: number;
            code: string;
            name: string;
            sellingPrice: number;
            costPrice: number | null;
            /** Format: int32 */
            stockQty: number;
            active: boolean;
            /** Format: int64 */
            version: number;
        };
        UpdateOldBottleBrandRequest: {
            bottleTypeCode: string;
            note?: string;
            active?: boolean;
            /** Format: int64 */
            version?: number;
        };
        OldBottleBrandResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            bottleTypeCode: string;
            bottleTypeName: string;
            note: string | null;
            active: boolean;
            /** Format: date */
            addedOn: string;
            /** Format: int32 */
            takenIn: number | null;
            /** Format: int64 */
            version: number;
        };
        UpdateCustomerTypeRequest: {
            description: string;
            active: boolean;
            /** Format: int64 */
            version: number;
        };
        CustomerTypeResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            description: string | null;
            active: boolean;
            /** Format: int64 */
            version: number;
        };
        UpdateBottleTypeRequest: {
            name: string;
            active?: boolean;
            /** Format: int64 */
            version?: number;
        };
        BottleTypeResponse: {
            code: string;
            name: string;
            litres: number;
            active: boolean;
            deposit: number | null;
            /** Format: int32 */
            inCirculation: number | null;
            /** Format: int64 */
            version: number;
        };
        AreaRequest: {
            name: string;
            active?: boolean;
            /** Format: int64 */
            version?: number;
        };
        AreaResponse: {
            /** Format: int64 */
            id: number;
            name: string;
            active: boolean;
            /** Format: int64 */
            version: number;
        };
        CreateUserRequest: {
            fullName: string;
            username: string;
            /** @enum {string} */
            role: "ADMIN" | "ACCOUNTANT" | "DELIVERY_STAFF";
            phone?: string;
            temporaryPassword: string;
        };
        ResetPasswordResponse: {
            user: components["schemas"]["UserResponse"];
            temporaryPassword: string;
        };
        CreateProductRequest: {
            name: string;
            sellingPrice: number;
            costPrice?: number;
            /** Format: int32 */
            openingStock?: number;
            active?: boolean;
        };
        SetPriceRequest: {
            /** @enum {string} */
            kind: "WATER" | "DEPOSIT";
            bottleTypeCode: string;
            /** Format: int64 */
            customerTypeId?: number;
            price: number;
            /** Format: date */
            effectiveFrom: string;
            reason: string;
        };
        PriceHistoryRow: {
            /** Format: int64 */
            id: number;
            kind: string;
            bottleTypeCode: string;
            /** Format: int64 */
            customerTypeId: number | null;
            label: string;
            price: number;
            /** Format: date */
            effectiveFrom: string;
            reason: string;
            createdBy: string;
            createdByName: string | null;
            /** Format: date-time */
            createdAt: string;
            status: string;
        };
        CreateOldBottleBrandRequest: {
            name: string;
            bottleTypeCode: string;
            note?: string;
        };
        CreateCustomerTypeRequest: {
            name: string;
            description?: string;
        };
        CreateBottleTypeRequest: {
            name: string;
            litres: number;
            active?: boolean;
        };
        LoginRequest: {
            username: string;
            password: string;
        };
        MeResponse: {
            user: components["schemas"]["UserInfo"];
            mustChangePassword: boolean;
            landingPage: string;
            permissions: string[];
            menu: components["schemas"]["MenuModule"][];
        };
        MenuItem: {
            key: string;
            title: string;
            path: string;
            view: boolean;
        };
        MenuModule: {
            module: string;
            icon: string;
            hidden: boolean;
            group: boolean;
            items: components["schemas"]["MenuItem"][];
        };
        UserInfo: {
            /** Format: int64 */
            id: number;
            username: string;
            fullName: string;
            role: string;
            roleName: string;
        };
        ChangePasswordRequest: {
            currentPassword: string;
            newPassword: string;
        };
        Cell: {
            level: string;
            note: string | null;
        };
        RoleColumn: {
            role: string;
            roleName: string;
        };
        RolesMatrixResponse: {
            roles: components["schemas"]["RoleColumn"][];
            rows: components["schemas"]["Row"][];
        };
        Row: {
            area: string;
            access: components["schemas"]["Cell"][];
        };
        PriceBottle: {
            code: string;
            name: string;
        };
        PriceCell: {
            key: string;
            kind: string;
            bottleTypeCode: string;
            /** Format: int64 */
            customerTypeId: number | null;
            current: components["schemas"]["PriceValue"];
            next: components["schemas"]["PriceValue"];
            confirmed: boolean;
        };
        PriceCustomerType: {
            /** Format: int64 */
            id: number;
            name: string;
        };
        PriceMatrixResponse: {
            /** Format: date */
            date: string;
            bottleTypes: components["schemas"]["PriceBottle"][];
            customerTypes: components["schemas"]["PriceCustomerType"][];
            water: components["schemas"]["PriceCell"][];
            deposits: components["schemas"]["PriceCell"][];
        };
        PriceValue: {
            /** Format: int64 */
            entryId: number;
            price: number;
            /** Format: date */
            effectiveFrom: string;
        };
        AuditEntryResponse: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            ts: string;
            username: string | null;
            /** @description The user's full name, when the user still exists */
            fullName: string | null;
            role: string | null;
            roleName: string | null;
            action: string;
            entity: string;
            ref: string | null;
            details: string | null;
        };
        PageResponseAuditEntryResponse: {
            items: components["schemas"]["AuditEntryResponse"][];
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            size: number;
            /** Format: int64 */
            total: number;
        };
        AuditFilterOptions: {
            users: components["schemas"]["UserOption"][];
            actions: string[];
            entities: string[];
        };
        UserOption: {
            username: string;
            fullName: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JsonNode"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                group: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JsonNode"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JsonNode"];
                };
            };
        };
    };
    update_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductResponse"];
                };
            };
        };
    };
    update_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOldBottleBrandRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OldBottleBrandResponse"];
                };
            };
        };
    };
    updateCustomerType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCustomerTypeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerTypeResponse"];
                };
            };
        };
    };
    update_4: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBottleTypeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BottleTypeResponse"];
                };
            };
        };
    };
    updateArea: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResetPasswordResponse"];
                };
            };
        };
    };
    deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    activate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logoImage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    uploadLogo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JsonNode"];
                };
            };
        };
    };
    removeLogo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["JsonNode"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductResponse"][];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ProductResponse"];
                };
            };
        };
    };
    setPrice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPriceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceHistoryRow"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OldBottleBrandResponse"][];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOldBottleBrandRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OldBottleBrandResponse"];
                };
            };
        };
    };
    customerTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerTypeResponse"][];
                };
            };
        };
    };
    createCustomerType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCustomerTypeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CustomerTypeResponse"];
                };
            };
        };
    };
    list_3: {
        parameters: {
            query?: {
                activeOnly?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BottleTypeResponse"][];
                };
            };
        };
    };
    create_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBottleTypeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BottleTypeResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    areas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaResponse"][];
                };
            };
        };
    };
    createArea: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AreaResponse"];
                };
            };
        };
    };
    matrix: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["RolesMatrixResponse"];
                };
            };
        };
    };
    history: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceHistoryRow"][];
                };
            };
        };
    };
    current: {
        parameters: {
            query?: {
                date?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PriceMatrixResponse"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
                user?: string;
                action?: "CREATE" | "UPDATE" | "APPROVE" | "REVERSE" | "IMPORT" | "LOGIN" | "LOGOUT";
                entity?: string;
                q?: string;
                page?: number;
                size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseAuditEntryResponse"];
                };
            };
        };
    };
    filters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuditFilterOptions"];
                };
            };
        };
    };
}
